version: "3.4"
services:
  envcan:
    build: ./
    restart: always
    volumes:
     - ./music:/root/retro-env-can-weather-chan/music
     - ./cfg:/root/retro-env-can-weather-chan/cfg
    ports:
      - 8600:8600
    environment: 
      - TZ=America/Winnipeg
