export const MAX_CONDITION_LENGTH = 13;
export const MAX_US_FORECAST_CONDITION_LENGTH = 12;
export const CONDITIONS_EVENT_STREAM_INTERVAL = 5 * 1000;
export const CONDITIONS_EVENT_STREAM_CONDITION_UPDATE_EVENT = "condition_update";
export const CONDITIONS_WIND_SPEED_CALM = "calm";
