export const EVENT_BUS_CONFIG_CHANGE_SUFFIX = "config:";
export const EVENT_BUS_CONFIG_CHANGE_PRIMARY_LOCATION = EVENT_BUS_CONFIG_CHANGE_SUFFIX + "primary_location";
export const EVENT_BUS_CONFIG_CHANGE_AIR_QUALITY_STATION = EVENT_BUS_CONFIG_CHANGE_SUFFIX + "air_quality";
export const EVENT_BUS_CONFIG_CHANGE_CLIMATE_NORMALS = EVENT_BUS_CONFIG_CHANGE_SUFFIX + "climate_normals";
export const EVENT_BUS_CONFIG_CHANGE_HISTORICAL_TEMP_PRECIP = EVENT_BUS_CONFIG_CHANGE_SUFFIX + "historical_temp_precip";
export const EVENT_BUS_CONFIG_CHANGE_PROVINCE_TRACKING = EVENT_BUS_CONFIG_CHANGE_SUFFIX + "province_tracking";
