const FORECAST_PREFIX_MAX_LENGTH = 22;
const FORECAST_TWO_LINE_MAX_LENGTH = 64;
const FORECAST_THREE_LINE_MAX_LENGTH = 96;
const FORECAST_FOUR_LINE_MAX_LENGTH = 128;

export const FORECAST_THREE_LINE_WITH_PREFIX_MAX_LENGTH = FORECAST_THREE_LINE_MAX_LENGTH - FORECAST_PREFIX_MAX_LENGTH;
export const FORECAST_FOUR_LINE_WITH_PREFIX_MAX_LENGTH = FORECAST_FOUR_LINE_MAX_LENGTH - FORECAST_PREFIX_MAX_LENGTH;
export const FORECAST_TWO_LINE_WITH_PREFIX_MAX_LENGTH = FORECAST_TWO_LINE_MAX_LENGTH - FORECAST_PREFIX_MAX_LENGTH;
