name: Test & Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "**.ts"
      - "**.test.ts"
      - "**.json"
      - "**.yml"
      - "yarn.lock"
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "**.ts"
      - "**.test.ts"
      - "**.json"
      - "**.yml"
      - "yarn.lock"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  install-cache:
    name: "Generate Cache"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install --force --non-interactive

  unit-test:
    name: "Unit Testing"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x, 21.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run test
        run: |
          yarn test

  build:
    name: "Production Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x, 21.x]
      fail-fast: false
    needs: unit-test
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run build
        run: |
          yarn build:display
      - name: Get build version
        run: |
          BUILD_VERSION=$(cat package.json|grep version|head -1|awk -F: '{ print $2 }'|sed 's/[", ]//g')
          echo "build_version=v$BUILD_VERSION" >> $GITHUB_ENV
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build_version }}-${{ env.commit_hash }}-node-${{ matrix.node }}
          path: |
            src/api
            src/consts
            src/hooks
            src/lib
            src/routes
            src/types
            src/*.ts
            dist
            tsconfig.json
            package.json
            yarn.lock
            README.md
          retention-days: 1
